### PR TITLE
Add Neon with Drizzle, Prisma, and Node.js support

### PR DESCRIPTION
**Pull request by evanshortiss**
@jawj @kelvich can you take a look? Two outstanding questions:

1. Is there a seed script required? I don't see `prisma migrate` being called anywhere for other platforms, so maybe not?
2. Prisma runs into an issue when setting `neonConfig.webSocketConstructor = ws`. It appears that the [browser.js](https://github.com/websockets/ws/blob/master/package.json#L24) file is loaded. A [user in the Neon Discord](https://discord.com/channels/1176467419317940276/1237113662301274172) ran into this today, too, but we didn't get to the bottom of it. It seems to happen when runtime is `edge`

Tested using these commands 

```bash
export NEON_DATABASE_URL='postgresql://user:pass@hostname/neondb?sslmode=require' 
npx prisma migrate dev
npm run dev
```

### CODE REVIEW

**Comment by kelvich** [comment]
Why does this PR includes prisma-client sources? can't in be just `npm install @prisma/client`?

**Comment by jawj** [comment]
I'm a little bit confused about what environment(s) this is supposed to run in. Is it both edge functions (i.e. v8 isolates, has WebSockets, no TCP) and lambdas (i.e. Node, has TCP, no WebSockets)?

In V8 isolates things will likely go wrong if you even try to import `ws` or `undici`, and certainly if you pass the relevant WebSocket constructor to our library.

In Node/Lambda I think things will go wrong _unless_ you do both those things.

**Comment by leerob** [comment]
@jawj it's both:

- Edge: https://edge-runtime.vercel.app/
- Serverless Node.js: MicroVM / Lambda

**Comment by evanshortiss** [comment]
@kelvich can you clarify what you mean? 

Do you mean why the relative import for the Prisma client? With Prisma you need to generate a custom client within your project. Usually, it's not checked in AFAIK, but in this repository, I believe it's necessary since we don't control build/deploy - you can see [other platforms doing it too in the repo](https://github.com/vercel-labs/function-database-latency).

**Comment by evanshortiss** [comment]
@jawj, right, and I'm not using the `Pool` constructor. I don't need `ws` either way. This is what happens when coding late.  Removed it 😄

**Comment by leerob** [comment]
CleanShot 2024-05-08 at 20 54 43@2x

Hmm, I don't see it here yet. Just me?

**Pull request merged**
